### ISSUE TITLE
State of analog input pins used to read photosensors

### ISSUE THREAD

**Issue by david-i** [TheSaturdayThing/laser_harp_arduino#1]
- Are the input pins floating? Should they have pull-ups?
- Do the trigger levels for detecting sensor on/off need to be auto-calibrated based on changes in ambient room light?

**Comment by MariamRegragui** [comment]
> * Are the input pins floating? Should they have pull-ups?  I think we are using a pull-down resistor because we got a 10kOhms resistor that  goes from GND to the pin, and the pull-up resistors should go from the 5v to the pin. (not sure about it :-) )
> * Do the trigger levels for detecting sensor on/off need to be auto-calibrated based on changes in ambient room light? Yes, in fact when you calibrate with the lasers on, the notes play when they receive back the light of the lasers, but when you calibrate with the ambient room light and then turn on the lasers, the notes play when the photoresistors loose the signal of the light of the lasers.

**Comment by david-i** [comment]
Since this question has 2 parts and you have answered the one about the input pins, I will close this and open a separate item on the sensor calibration.
